apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-default-np
spec:
  rules:
  - name: ns-default-deny
    match:
      any:
      - resources:
          kinds: [Namespace]
    generate:
      kind: NetworkPolicy
      name: default-deny
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: default-deny
        spec:
          podSelector: {}
          policyTypes: [Ingress, Egress]